import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

const virtualModuleId = 'virtual:specter/refs'
const resolvedVirtualModuleId = `\0${virtualModuleId}`
const generatedDtsPath = path.join('src', 'specter-refs.generated.d.ts')

type RefKind = 'command' | 'projection'

type SliceRef = {
  filePath: string
  importName: string
  importPath: string
  kind: RefKind
  name: string
  exportName: string
}

export function specterRefsPlugin(): Plugin {
  let root = process.cwd()

  return {
    name: 'specter-refs',
    configResolved(config) {
      root = config.root
      writeDeclaration(root)
    },
    buildStart() {
      writeDeclaration(root)
    },
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
    },
    load(id) {
      if (id !== resolvedVirtualModuleId) {
        return
      }

      const refs = collectRefs(root)

      return `${refs
        .map(
          (ref) =>
            `export const ${ref.exportName} = { name: ${JSON.stringify(ref.name)} }`,
        )
        .join('\n')}\n`
    },
    configureServer(server) {
      server.watcher.add(path.join(root, 'src', 'features'))
    },
    handleHotUpdate(context) {
      if (!isSliceFile(context.file)) {
        return
      }

      writeDeclaration(root)

      const module = context.server.moduleGraph.getModuleById(
        resolvedVirtualModuleId,
      )

      if (module) {
        context.server.moduleGraph.invalidateModule(module)
      }

      context.server.ws.send({ type: 'full-reload' })
    },
  }
}

function writeDeclaration(root: string) {
  const filePath = path.join(root, generatedDtsPath)
  const source = generateDeclaration(root)
  const current = existsSync(filePath) ? readFileSync(filePath, 'utf8') : ''

  if (current === source) {
    return
  }

  mkdirSync(path.dirname(filePath), { recursive: true })
  writeFileSync(filePath, source)
}

function generateDeclaration(root: string) {
  const refs = collectRefs(root)
  const exports = refs.map((ref) => {
    const refType = ref.kind === 'command' ? 'CommandRef' : 'ProjectionRef'

    return [
      `  export const ${ref.exportName}: import('./lib2').${refType}<`,
      `    typeof import('${ref.importPath}').default`,
      '  >',
    ].join('\n')
  })

  return [
    '// This file is generated by specterRefsPlugin in vite.config.ts.',
    "declare module 'virtual:specter/refs' {",
    ...exports,
    '}',
    '',
  ].join('\n')
}

function collectRefs(root: string) {
  const featuresRoot = path.join(root, 'src', 'features')
  const refs: SliceRef[] = []
  const names = new Map<string, string>()

  for (const filePath of walk(featuresRoot)) {
    if (!isSliceFile(filePath)) {
      continue
    }

    const source = readFileSync(filePath, 'utf8')

    if (!source.includes('/lib2') && !source.includes('lib2')) {
      continue
    }

    const ref = parseSliceRef(root, filePath, source)

    if (!ref) {
      continue
    }

    const existingPath = names.get(ref.name)

    if (existingPath) {
      throw new Error(
        `Duplicate Specter slice name "${ref.name}" in ${relative(root, filePath)} and ${relative(root, existingPath)}`,
      )
    }

    names.set(ref.name, filePath)
    refs.push(ref)
  }

  return refs.sort((a, b) => a.name.localeCompare(b.name))
}

function parseSliceRef(
  root: string,
  filePath: string,
  source: string,
): SliceRef | undefined {
  const specMatch = source.match(
    /\bconst\s+([A-Za-z_$][\w$]*)\s*=\s*create(Command|Projection|Reaction)Slice\(\s*['"]([^'"]+)['"]/,
  )

  if (!specMatch) {
    throw new Error(
      `Expected ${relative(root, filePath)} to create its default slice with createCommandSlice, createProjectionSlice, or createReactionSlice`,
    )
  }

  const localName = specMatch[1]
  const builderKind = specMatch[2]
  const sliceName = specMatch[3]

  if (!localName || !builderKind || !sliceName) {
    throw new Error(
      `Could not parse slice registration in ${relative(root, filePath)}`,
    )
  }

  const defaultMatch = source.match(/\bexport\s+default\s+([A-Za-z_$][\w$]*)\b/)
  const defaultName = defaultMatch?.[1]

  if (defaultName !== localName) {
    throw new Error(
      `Expected ${relative(root, filePath)} to default-export ${localName}`,
    )
  }

  const kind = getRefKind(builderKind)

  if (!kind) {
    return
  }

  if (!isIdentifier(sliceName)) {
    throw new Error(
      `Slice name "${sliceName}" in ${relative(root, filePath)} is not a valid ref export name`,
    )
  }

  const relativeToSrc = path.relative(path.join(root, 'src'), filePath)
  const importPath = `./${withoutExtension(toPosix(relativeToSrc))}`

  return {
    filePath,
    importName: `${sliceName}Slice`,
    importPath,
    kind,
    name: sliceName,
    exportName: sliceName,
  }
}

function getRefKind(builderKind: string): RefKind | undefined {
  switch (builderKind) {
    case 'Command':
      return 'command'
    case 'Projection':
      return 'projection'
    case 'Reaction':
      return
    default:
      throw new Error(`Unknown slice builder kind ${builderKind}`)
  }
}

function walk(directory: string): string[] {
  if (!existsSync(directory)) {
    return []
  }

  const filePaths: string[] = []

  for (const entry of readdirSync(directory)) {
    const entryPath = path.join(directory, entry)
    const stats = statSync(entryPath)

    if (stats.isDirectory()) {
      filePaths.push(...walk(entryPath))
    } else if (stats.isFile()) {
      filePaths.push(entryPath)
    }
  }

  return filePaths
}

function isSliceFile(filePath: string) {
  return toPosix(filePath).endsWith('/slice.ts')
}

function isIdentifier(value: string) {
  return /^[A-Za-z_$][\w$]*$/.test(value)
}

function relative(root: string, filePath: string) {
  return toPosix(path.relative(root, filePath))
}

function toPosix(filePath: string) {
  return filePath.split(path.sep).join('/')
}

function withoutExtension(filePath: string) {
  return filePath.replace(/\.tsx?$/, '')
}
