export function renderCollectorHtml(basePath = '') {
  const apiBase = JSON.stringify(basePath)
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Specter runtime observability</title>
<style>
:root{font:14px/1.45 system-ui;color:#172033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}main{max-width:1400px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:end;gap:16px}h1{margin:0;font-size:24px}p{color:#5d6677}.cards{display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:12px;margin:20px 0}.card,section{background:white;border:1px solid #dfe4ec;border-radius:10px;padding:16px}.value{font-size:24px;font-weight:700}.filters{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.filters input{width:150px}input{padding:8px;border:1px solid #c9d0db;border-radius:6px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #edf0f5;vertical-align:top}code{font-size:12px}.failed{color:#b42318;font-weight:600}.muted{color:#697386}section{margin-bottom:16px}@media(max-width:800px){.cards{grid-template-columns:1fr 1fr}.table{overflow:auto}}
</style></head><body><main>
<header><div><h1>Specter runtime observability</h1><p>Language-neutral live runtime activity and causal traces.</p></div></header>
<div class="filters"><input id="application" placeholder="application"><input id="environment" placeholder="environment"><input id="instance" placeholder="instance"><input id="eventLog" placeholder="Event Log"><input id="kind" placeholder="kind"></div>
<div class="cards"><div class="card"><div class="muted">Observations</div><div class="value" id="observations">—</div></div><div class="card"><div class="muted">Failures</div><div class="value" id="failures">—</div></div><div class="card"><div class="muted">Dropped</div><div class="value" id="dropped">—</div></div><div class="card"><div class="muted">Sources</div><div class="value" id="sources">—</div></div></div>
<section><h2>Runtime sources and projection lag</h2><div class="table"><table><thead><tr><th>Application</th><th>Environment</th><th>Runtime</th><th>Instance / Event Log</th><th>Lag</th><th>Failures</th></tr></thead><tbody id="sourceRows"></tbody></table></div></section>
<section><h2>Live activity</h2><div class="table"><table><thead><tr><th>Order</th><th>Source</th><th>Kind</th><th>Operation</th><th>Observed</th></tr></thead><tbody id="activity"></tbody></table></div></section>
<section id="traceSection" hidden><h2>Causal trace</h2><pre id="trace"></pre></section>
</main><script type="module">
const base=${apiBase};const rows=new Map();const byId=(id)=>document.getElementById(id);const esc=(value)=>String(value??'');
function matches(item){return (!byId('application').value.trim()||item.source.application===byId('application').value.trim())&&(!byId('environment').value.trim()||item.source.environment===byId('environment').value.trim())&&(!byId('instance').value.trim()||item.source.instanceId===byId('instance').value.trim())&&(!byId('eventLog').value.trim()||item.source.eventLogId===byId('eventLog').value.trim())&&(!byId('kind').value.trim()||item.kind===byId('kind').value.trim())}
function renderRows(items){for(const item of items)rows.set(item.observationId,item);const list=[...rows.values()].filter(matches).sort((a,b)=>b.collectorOrder-a.collectorOrder).slice(0,200);byId('activity').replaceChildren(...list.map(item=>{const tr=document.createElement('tr');for(const value of [item.collectorOrder,item.source.application+' / '+item.source.instanceId,item.kind,item.operationId,item.observedAt]){const td=document.createElement('td');if(value===item.operationId){const button=document.createElement('button');button.textContent=esc(value);button.onclick=()=>showTrace(value);td.append(button)}else td.textContent=esc(value);if(item.outcome==='failed'||item.outcome==='rejected')td.classList.add('failed');tr.append(td)}return tr}))}
function renderSources(sources){byId('sourceRows').replaceChildren(...sources.map(item=>{const tr=document.createElement('tr');for(const value of [item.source.application,item.source.environment,item.source.runtimeLanguage+' '+item.source.runtimeVersion,item.source.instanceId+' / '+item.source.eventLogId,item.projectionLag,item.failureCount]){const td=document.createElement('td');td.textContent=esc(value);tr.append(td)}return tr}))}
async function overview(){const value=await fetch(base+'/v1/overview').then(r=>r.json());byId('observations').textContent=value.observationCount;byId('failures').textContent=value.failureCount;byId('dropped').textContent=value.droppedObservationCount;byId('sources').textContent=value.sources.length;renderSources(value.sources);renderRows(value.recent)}
async function showTrace(id){const value=await fetch(base+'/v1/traces/'+encodeURIComponent(id)).then(r=>r.json());byId('traceSection').hidden=false;byId('trace').textContent=JSON.stringify(value,null,2)}
for(const id of ['application','environment','instance','eventLog','kind'])byId(id).addEventListener('input',()=>renderRows([]));await overview();const stream=new EventSource(base+'/v1/stream');stream.addEventListener('activity',event=>{renderRows([JSON.parse(event.data)]);void overview()});
</script></body></html>`
}
