# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

nodes:
  - id: migrate-specter-json-specs
    name: Migrate Specter Slice specifications and implementations
    type: automatic
    steps:
      - name: "Use @specter-ts/spec and generated JSON implementations"
        js-ast-grep:
          js_file: scripts/codemod.ts
          base_path: "."
          language: "typescript"
          include:
            - "**/{spec,impl}.ts"
          exclude:
            - "**/node_modules/**"
            - "**/dist/**"
            - "**/build/**"
