export { createSpecterApp } from './app'
export type {
  CommandExecution,
  CommandExecutionOptions,
  QuerySubscriptionOptions,
  SpecterCausality,
  SpecterApp,
  SpecterAppConfig,
  SpecterAppConfigOf,
  SpecterCommandEnvelope,
  SpecterCommandType,
  SpecterObservation,
  SpecterEventOrderRange,
  SpecterEventReference,
  SpecterOperationOptions,
  SpecterObserver,
  SpecterQueryEnvelope,
  SpecterQueryResult,
  SpecterQueryType,
  SpecterRuntimeOptions,
} from './app'
export {
  ReactionRunFailure,
  specterErrorCodes,
  SpecterCommandRejectedError,
  SpecterError,
  SpecterEventLogOrderError,
  SpecterIdempotencyConflictError,
  SpecterInfrastructureError,
  SpecterInvalidCommandOptionsError,
  SpecterInvalidInputError,
  SpecterInvalidOutputError,
  SpecterUnknownCommandError,
  SpecterUnknownEventError,
  SpecterUnknownQueryError,
  SpecterVersionConflictError,
} from './errors'
export type {
  ReactionRunFailureDetail,
  SpecterErrorCode,
  SpecterOperationKind,
} from './errors'
