import { createQuerySlice, event } from '@specter-ts/spec'
export default createQuerySlice('roomScheduleQuery')
  .description('Shows room schedules with filtered bookings.')
  .scenarios(
    {
      description: 'Returns rooms with bookings for the requested day.',
      given: [
        event('room-created', {
          roomId: 'room-1',
          name: 'Library',
          capacity: 6,
          location: 'Floor 1',
        }),
        event('booking-requested', {
          bookingId: 'booking-1',
          roomId: 'room-1',
          requesterEmail: 'ada@example.com',
          requesterName: 'Ada',
          purpose: 'Planning',
          startsAt: '2026-06-01T09:00:00.000Z',
          endsAt: '2026-06-01T10:00:00.000Z',
        }),
      ],
      when: { day: '2026-06-01', status: 'all' },
      expect: [
        {
          roomId: 'room-1',
          name: 'Library',
          capacity: 6,
          location: 'Floor 1',
          retired: false,
          bookings: [
            {
              bookingId: 'booking-1',
              roomId: 'room-1',
              requesterEmail: 'ada@example.com',
              requesterName: 'Ada',
              purpose: 'Planning',
              startsAt: '2026-06-01T09:00:00.000Z',
              endsAt: '2026-06-01T10:00:00.000Z',
              status: 'pending',
            },
          ],
        },
      ],
    },
    {
      description: 'Projects lifecycle changes onto room schedules.',
      given: [
        event('room-created', {
          roomId: 'room-1',
          name: 'Library',
          capacity: 6,
          location: 'Floor 1',
        }),
        event('room-retired', { roomId: 'room-1' }),
        event('booking-requested', {
          bookingId: 'booking-1',
          roomId: 'room-1',
          requesterEmail: 'ada@example.com',
          requesterName: 'Ada',
          purpose: 'Planning',
          startsAt: '2026-06-01T09:00:00.000Z',
          endsAt: '2026-06-01T10:00:00.000Z',
        }),
        event('booking-approved', {
          bookingId: 'booking-1',
          approverEmail: 'lin@example.com',
          approverName: 'Lin',
        }),
        event('booking-checked-in', {
          bookingId: 'booking-1',
          checkedInByEmail: 'ada@example.com',
        }),
        event('room-released', {
          bookingId: 'booking-1',
          releasedByEmail: 'ada@example.com',
        }),
        event('booking-requested', {
          bookingId: 'booking-2',
          roomId: 'room-1',
          requesterEmail: 'lin@example.com',
          requesterName: 'Lin',
          purpose: 'Review',
          startsAt: '2026-06-01T11:00:00.000Z',
          endsAt: '2026-06-01T12:00:00.000Z',
        }),
        event('booking-rejected', {
          bookingId: 'booking-2',
          approverEmail: 'grace@example.com',
          approverName: 'Grace',
          reason: 'No',
        }),
        event('booking-requested', {
          bookingId: 'booking-3',
          roomId: 'room-1',
          requesterEmail: 'grace@example.com',
          requesterName: 'Grace',
          purpose: 'Retro',
          startsAt: '2026-06-01T12:00:00.000Z',
          endsAt: '2026-06-01T13:00:00.000Z',
        }),
        event('booking-canceled', {
          bookingId: 'booking-3',
          canceledByEmail: 'grace@example.com',
          reason: 'Changed plans',
        }),
        event('booking-requested', {
          bookingId: 'booking-4',
          roomId: 'room-1',
          requesterEmail: 'alan@example.com',
          requesterName: 'Alan',
          purpose: 'Demo',
          startsAt: '2026-06-01T13:00:00.000Z',
          endsAt: '2026-06-01T14:00:00.000Z',
        }),
        event('booking-rescheduled', {
          bookingId: 'booking-4',
          roomId: 'room-1',
          startsAt: '2026-06-01T14:00:00.000Z',
          endsAt: '2026-06-01T15:00:00.000Z',
        }),
      ],
      when: { day: '2026-06-01', status: 'all' },
      expect: [
        {
          roomId: 'room-1',
          name: 'Library',
          capacity: 6,
          location: 'Floor 1',
          retired: true,
          bookings: [
            {
              bookingId: 'booking-1',
              roomId: 'room-1',
              requesterEmail: 'ada@example.com',
              requesterName: 'Ada',
              purpose: 'Planning',
              startsAt: '2026-06-01T09:00:00.000Z',
              endsAt: '2026-06-01T10:00:00.000Z',
              status: 'released',
            },
            {
              bookingId: 'booking-2',
              roomId: 'room-1',
              requesterEmail: 'lin@example.com',
              requesterName: 'Lin',
              purpose: 'Review',
              startsAt: '2026-06-01T11:00:00.000Z',
              endsAt: '2026-06-01T12:00:00.000Z',
              status: 'rejected',
            },
            {
              bookingId: 'booking-3',
              roomId: 'room-1',
              requesterEmail: 'grace@example.com',
              requesterName: 'Grace',
              purpose: 'Retro',
              startsAt: '2026-06-01T12:00:00.000Z',
              endsAt: '2026-06-01T13:00:00.000Z',
              status: 'canceled',
            },
            {
              bookingId: 'booking-4',
              roomId: 'room-1',
              requesterEmail: 'alan@example.com',
              requesterName: 'Alan',
              purpose: 'Demo',
              startsAt: '2026-06-01T14:00:00.000Z',
              endsAt: '2026-06-01T15:00:00.000Z',
              status: 'pending',
            },
          ],
        },
      ],
    },
  )
