// This file is generated by specterRefsPlugin in vite.config.ts.
declare module 'virtual:specter/refs' {
  export const addTodo: import('@specter/core').CommandRef<
    typeof import('./features/todos/add-todo/slice').default
  >
  export const changeTodoCompletion: import('@specter/core').CommandRef<
    typeof import('./features/todos/change-todo-completion/slice').default
  >
  export const createTodoCheer: import('@specter/core').CommandRef<
    typeof import('./features/todos/create-todo-cheer/slice').default
  >
  export const removeTodo: import('@specter/core').CommandRef<
    typeof import('./features/todos/remove-todo/slice').default
  >
  export const todoCheers: import('@specter/core').QueryRef<
    typeof import('./features/todos/todo-cheers/slice').default
  >
  export const todosQuery: import('@specter/core').QueryRef<
    typeof import('./features/todos/todos-query/slice').default
  >
}
