/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariantsRouteImport } from './routes/variants'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariantsVerticalSlicesRouteImport } from './routes/variants/vertical-slices'
import { Route as VariantsSpecsBecomeAppsRouteImport } from './routes/variants/specs-become-apps'
import { Route as VariantsSpecTestHarnessRouteImport } from './routes/variants/spec-test-harness'
import { Route as VariantsSpecCompilerRouteImport } from './routes/variants/spec-compiler'
import { Route as VariantsBeforeCodeShapeRouteImport } from './routes/variants/before-code-shape'
import { Route as VariantsAiImplementationHarnessRouteImport } from './routes/variants/ai-implementation-harness'

const VariantsRoute = VariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsVerticalSlicesRoute = VariantsVerticalSlicesRouteImport.update({
  id: '/vertical-slices',
  path: '/vertical-slices',
  getParentRoute: () => VariantsRoute,
} as any)
const VariantsSpecsBecomeAppsRoute = VariantsSpecsBecomeAppsRouteImport.update({
  id: '/specs-become-apps',
  path: '/specs-become-apps',
  getParentRoute: () => VariantsRoute,
} as any)
const VariantsSpecTestHarnessRoute = VariantsSpecTestHarnessRouteImport.update({
  id: '/spec-test-harness',
  path: '/spec-test-harness',
  getParentRoute: () => VariantsRoute,
} as any)
const VariantsSpecCompilerRoute = VariantsSpecCompilerRouteImport.update({
  id: '/spec-compiler',
  path: '/spec-compiler',
  getParentRoute: () => VariantsRoute,
} as any)
const VariantsBeforeCodeShapeRoute = VariantsBeforeCodeShapeRouteImport.update({
  id: '/before-code-shape',
  path: '/before-code-shape',
  getParentRoute: () => VariantsRoute,
} as any)
const VariantsAiImplementationHarnessRoute =
  VariantsAiImplementationHarnessRouteImport.update({
    id: '/ai-implementation-harness',
    path: '/ai-implementation-harness',
    getParentRoute: () => VariantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/variants': typeof VariantsRouteWithChildren
  '/variants/ai-implementation-harness': typeof VariantsAiImplementationHarnessRoute
  '/variants/before-code-shape': typeof VariantsBeforeCodeShapeRoute
  '/variants/spec-compiler': typeof VariantsSpecCompilerRoute
  '/variants/spec-test-harness': typeof VariantsSpecTestHarnessRoute
  '/variants/specs-become-apps': typeof VariantsSpecsBecomeAppsRoute
  '/variants/vertical-slices': typeof VariantsVerticalSlicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/variants': typeof VariantsRouteWithChildren
  '/variants/ai-implementation-harness': typeof VariantsAiImplementationHarnessRoute
  '/variants/before-code-shape': typeof VariantsBeforeCodeShapeRoute
  '/variants/spec-compiler': typeof VariantsSpecCompilerRoute
  '/variants/spec-test-harness': typeof VariantsSpecTestHarnessRoute
  '/variants/specs-become-apps': typeof VariantsSpecsBecomeAppsRoute
  '/variants/vertical-slices': typeof VariantsVerticalSlicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/variants': typeof VariantsRouteWithChildren
  '/variants/ai-implementation-harness': typeof VariantsAiImplementationHarnessRoute
  '/variants/before-code-shape': typeof VariantsBeforeCodeShapeRoute
  '/variants/spec-compiler': typeof VariantsSpecCompilerRoute
  '/variants/spec-test-harness': typeof VariantsSpecTestHarnessRoute
  '/variants/specs-become-apps': typeof VariantsSpecsBecomeAppsRoute
  '/variants/vertical-slices': typeof VariantsVerticalSlicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs'
    | '/variants'
    | '/variants/ai-implementation-harness'
    | '/variants/before-code-shape'
    | '/variants/spec-compiler'
    | '/variants/spec-test-harness'
    | '/variants/specs-become-apps'
    | '/variants/vertical-slices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/variants'
    | '/variants/ai-implementation-harness'
    | '/variants/before-code-shape'
    | '/variants/spec-compiler'
    | '/variants/spec-test-harness'
    | '/variants/specs-become-apps'
    | '/variants/vertical-slices'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/docs'
    | '/variants'
    | '/variants/ai-implementation-harness'
    | '/variants/before-code-shape'
    | '/variants/spec-compiler'
    | '/variants/spec-test-harness'
    | '/variants/specs-become-apps'
    | '/variants/vertical-slices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRoute
  VariantsRoute: typeof VariantsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/variants': {
      id: '/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/vertical-slices': {
      id: '/variants/vertical-slices'
      path: '/vertical-slices'
      fullPath: '/variants/vertical-slices'
      preLoaderRoute: typeof VariantsVerticalSlicesRouteImport
      parentRoute: typeof VariantsRoute
    }
    '/variants/specs-become-apps': {
      id: '/variants/specs-become-apps'
      path: '/specs-become-apps'
      fullPath: '/variants/specs-become-apps'
      preLoaderRoute: typeof VariantsSpecsBecomeAppsRouteImport
      parentRoute: typeof VariantsRoute
    }
    '/variants/spec-test-harness': {
      id: '/variants/spec-test-harness'
      path: '/spec-test-harness'
      fullPath: '/variants/spec-test-harness'
      preLoaderRoute: typeof VariantsSpecTestHarnessRouteImport
      parentRoute: typeof VariantsRoute
    }
    '/variants/spec-compiler': {
      id: '/variants/spec-compiler'
      path: '/spec-compiler'
      fullPath: '/variants/spec-compiler'
      preLoaderRoute: typeof VariantsSpecCompilerRouteImport
      parentRoute: typeof VariantsRoute
    }
    '/variants/before-code-shape': {
      id: '/variants/before-code-shape'
      path: '/before-code-shape'
      fullPath: '/variants/before-code-shape'
      preLoaderRoute: typeof VariantsBeforeCodeShapeRouteImport
      parentRoute: typeof VariantsRoute
    }
    '/variants/ai-implementation-harness': {
      id: '/variants/ai-implementation-harness'
      path: '/ai-implementation-harness'
      fullPath: '/variants/ai-implementation-harness'
      preLoaderRoute: typeof VariantsAiImplementationHarnessRouteImport
      parentRoute: typeof VariantsRoute
    }
  }
}

interface VariantsRouteChildren {
  VariantsAiImplementationHarnessRoute: typeof VariantsAiImplementationHarnessRoute
  VariantsBeforeCodeShapeRoute: typeof VariantsBeforeCodeShapeRoute
  VariantsSpecCompilerRoute: typeof VariantsSpecCompilerRoute
  VariantsSpecTestHarnessRoute: typeof VariantsSpecTestHarnessRoute
  VariantsSpecsBecomeAppsRoute: typeof VariantsSpecsBecomeAppsRoute
  VariantsVerticalSlicesRoute: typeof VariantsVerticalSlicesRoute
}

const VariantsRouteChildren: VariantsRouteChildren = {
  VariantsAiImplementationHarnessRoute: VariantsAiImplementationHarnessRoute,
  VariantsBeforeCodeShapeRoute: VariantsBeforeCodeShapeRoute,
  VariantsSpecCompilerRoute: VariantsSpecCompilerRoute,
  VariantsSpecTestHarnessRoute: VariantsSpecTestHarnessRoute,
  VariantsSpecsBecomeAppsRoute: VariantsSpecsBecomeAppsRoute,
  VariantsVerticalSlicesRoute: VariantsVerticalSlicesRoute,
}

const VariantsRouteWithChildren = VariantsRoute._addFileChildren(
  VariantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  VariantsRoute: VariantsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
