// This file is generated by specterRefsPlugin in vite.config.ts.
declare module 'virtual:specter/refs' {
  export const addTodo: import('./lib2').CommandRef<
    typeof import('./features/todos/add-todo/slice').default
  >
  export const changeTodoCompletion: import('./lib2').CommandRef<
    typeof import('./features/todos/change-todo-completion/slice').default
  >
  export const createTodoCheer: import('./lib2').CommandRef<
    typeof import('./features/todos/create-todo-cheer/slice').default
  >
  export const removeTodo: import('./lib2').CommandRef<
    typeof import('./features/todos/remove-todo/slice').default
  >
  export const todoCheers: import('./lib2').ProjectionRef<
    typeof import('./features/todos/todo-cheers/slice').default
  >
  export const todosProjection: import('./lib2').ProjectionRef<
    typeof import('./features/todos/todos-view/slice').default
  >
}
